import type { AppProps } from "next/app";
import { ChakraProvider, Flex } from "@chakra-ui/react";
import Head from "next/head";
import { Nav } from "@/components/Nav/Nav";

import hljs from "highlight.js/lib/core";
import javascript from "highlight.js/lib/languages/javascript";
import css from "highlight.js/lib/languages/css";
import "highlight.js/styles/atom-one-dark.css";

import { MDXProvider } from "@/lib/md/client";

hljs.registerLanguage("javascript", javascript);
hljs.registerLanguage("css", css);

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>next-mdx-chakra-site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider>
        <MDXProvider>
          <Flex flexDirection="column" minH="100vh">
            <Nav />
            <Component {...pageProps} />
          </Flex>
        </MDXProvider>
      </ChakraProvider>
    </>
  );
}
